<?php
CONST FOURNITURES = [
    "Cuisine" => [
        ["id" => 1, "nom" => "Etagère", "volume" => 0.3, "qte" => 0, "categorie" => "cuisine"],
        ["id" => 2, "nom" => "Etagère grande", "volume" => 1.0, "qte" => 0],
        ["id" => 3, "nom" => "Etagère moyenne", "volume" => 0.5, "qte" => 0],
        ["id" => 4, "nom" => "Etagère petite", "volume" => 0.5, "qte" => 0],
        ["id" => 5, "nom" => "Buffet bas (2 portes)", "volume" => 1.0, "qte" => 0],
        ["id" => 6, "nom" => "Buffet bas (3 4 portes)", "volume" => 1.6, "qte" => 0],
        ["id" => 7, "nom" => "Buffet bas (4/5 portes)", "volume" => 2.0, "qte" => 0],
        ["id" => 8, "nom" => "Buffet 2 corps (bas + haut)", "volume" => 2.5, "qte" => 0],
        ["id" => 9, "nom" => "Chaise", "volume" => 0.25, "qte" => 0],
        ["id" => 10, "nom" => "Chaise haute bébé", "volume" => 0.25, "qte" => 0],
        ["id" => 11, "nom" => "Chaise pliante", "volume" => 0.20, "qte" => 0],
        ["id" => 12, "nom" => "Congélateur grand", "volume" => 1.00, "qte" => 0],
        ["id" => 13, "nom" => "Congélateur standard", "volume" => 0.75, "qte" => 0],
        ["id" => 14, "nom" => "Congélateur petit", "volume" => 0.50, "qte" => 0],
        ["id" => 15, "nom" => "Cuisinière/Gazinière", "volume" => 0.50, "qte" => 0],
        ["id" => 16, "nom" => "Desserte (table)", "volume" => 1.05, "qte" => 0],
        ["id" => 17, "nom" => "Desserte (meuble)", "volume" => 0.50, "qte" => 0],
        ["id" => 18, "nom" => "Desserte (chariot)", "volume" => 0.35, "qte" => 0],
        ["id" => 19, "nom" => "Elément bas", "volume" => 0.60, "qte" => 0],
        ["id" => 20, "nom" => "Elément haut", "volume" => 0.60, "qte" => 0],
        ["id" => 21, "nom" => "Four", "volume" => 0.50, "qte" => 0],
        ["id" => 22, "nom" => "Four (mini) / micro ondes", "volume" => 0.25, "qte" => 0],
        ["id" => 23, "nom" => "Réfrigérateur (petit)", "volume" => 0.50, "qte" => 0],
        ["id" => 24, "nom" => "Réfrigérateur (standard)", "volume" => 1.00, "qte" => 0],
        ["id" => 25, "nom" => "Réfrigérateur (Grand)", "volume" => 1.50, "qte" => 0],
        ["id" => 26, "nom" => "Frigo américain", "volume" => 1.85, "qte" => 0],
        ["id" => 27, "nom" => "Frigo combiné", "volume" => 1.00, "qte" => 0],
        ["id" => 28, "nom" => "Lampadaire", "volume" => 0.25, "qte" => 0],
        ["id" => 29, "nom" => "Lampe de sol", "volume" => 0.25, "qte" => 0],
        ["id" => 30, "nom" => "Lampe de table", "volume" => 0.25, "qte" => 0],
        ["id" => 31, "nom" => "Lave vaisselle", "volume" => 0.50, "qte" => 0],
        ["id" => 32, "nom" => "Miroir / Tableau", "volume" => 0.10, "qte" => 0],
        ["id" => 33, "nom" => "Petit electroménager", "volume" => 0.04, "qte" => 0],
        ["id" => 34, "nom" => "Poubelle grande", "volume" => 0.55, "qte" => 0],
        ["id" => 35, "nom" => "Poubelle petite", "volume" => 0.15, "qte" => 0],
        ["id" => 36, "nom" => "Table grande", "volume" => 1.80, "qte" => 0],
        ["id" => 37, "nom" => "Table (petite)", "volume" => 1.15, "qte" => 0],
        ["id" => 38, "nom" => "Table (moyenne)", "volume" => 1.45, "qte" => 0],
        ["id" => 39, "nom" => "Tabouret", "volume" => 0.10, "qte" => 0],
        ["id" => 40, "nom" => "Tabouret de bar", "volume" => 0.30, "qte" => 0],
        ["id" => 41, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 42, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 43, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0],
        ["id" => 44, "nom" => "Cartons penderies", "volume" => 0.50, "qte" => 0]
    ],
    "Salle de Bain" => [
        ["id" => 45, "nom" => "Bac à linge", "volume" => 0.27, "qte" => 0, "categorie" => "Salle de bain"],
        ["id" => 46, "nom" => "Etendoir à linge (tancarville)", "volume" => 0.06, "qte" => 0],
        ["id" => 47, "nom" => "Miroir / Tableau", "volume" => 0.18, "qte" => 0],
        ["id" => 48, "nom" => "Lampe / Lampadaire / Lustre", "volume" => 0.25, "qte" => 0],
        ["id" => 49, "nom" => "Lave Linge / Sèche linge", "volume" => 0.50, "qte" => 0],
        ["id" => 50, "nom" => "Meuble colonne", "volume" => 1.00, "qte" => 0],
        ["id" => 51, "nom" => "Meuble bas (2 portes)", "volume" => 0.05, "qte" => 0],
        ["id" => 52, "nom" => "Meuble haut (2 portes)", "volume" => 0.50, "qte" => 0],
        ["id" => 53, "nom" => "Meuble pharmacie", "volume" => 0.05, "qte" => 0],
        ["id" => 54, "nom" => "Poubelle", "volume" => 0.13, "qte" => 0],
        ["id" => 55, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 56, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 57, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0],
        ["id" => 58, "nom" => "Cartons penderies", "volume" => 0.50, "qte" => 0]
    ],
    "salonSalleAManger" => [
        ["id" => 59, "nom" => "Pouf/Repose pieds (grand)", "volume" => 0.40, "qte" => 0, "categorie" => "Salon/Salle à manger"],
        ["id" => 60, "nom" => "Pouf/Repose pieds (petit)", "volume" => 0.10, "qte" => 0],
        ["id" => 61, "nom" => "Pouf Poire", "volume" => 0.80, "qte" => 0],
        ["id" => 62, "nom" => "Bibliothèque Grande", "volume" => 2.00, "qte" => 0],
        ["id" => 63, "nom" => "Bibliothèque Moyenne", "volume" => 1.00, "qte" => 0],
        ["id" => 64, "nom" => "Bibliothèque Petite", "volume" => 0.50, "qte" => 0],
        ["id" => 65, "nom" => "Buffet bas (2 portes)", "volume" => 1.00, "qte" => 0],
        ["id" => 66, "nom" => "Buffet bas (3/4 portes)", "volume" => 1.60, "qte" => 0],
        ["id" => 67, "nom" => "Buffet bas (4/5 portes)", "volume" => 2.00, "qte" => 0],
        ["id" => 68, "nom" => "Buffet 2 corps (bas + haut)", "volume" => 2.50, "qte" => 0],
        ["id" => 69, "nom" => "Chaise", "volume" => 0.25, "qte" => 0],
        ["id" => 70, "nom" => "Canapé d'Angle 4/5 places", "volume" => 2.50, "qte" => 0],
        ["id" => 71, "nom" => "Canapé d'angle 5/6 places", "volume" => 3.00, "qte" => 0],
        ["id" => 72, "nom" => "Canapé 2 places", "volume" => 2.00, "qte" => 0],
        ["id" => 73, "nom" => "Canapé 3 places", "volume" => 2.50, "qte" => 0],
        ["id" => 74, "nom" => "Clic clac / BZ", "volume" => 1.50, "qte" => 0],
        ["id" => 75, "nom" => "Fauteuil", "volume" => 1.00, "qte" => 0],
        ["id" => 76, "nom" => "Fauteuil voltaire", "volume" => 0.50, "qte" => 0],
        ["id" => 77, "nom" => "Fauteuil rotin", "volume" => 0.30, "qte" => 0],
        ["id" => 78, "nom" => "Guéridon", "volume" => 0.25, "qte" => 0],
        ["id" => 79, "nom" => "Lampadaire", "volume" => 0.25, "qte" => 0],
        ["id" => 80, "nom" => "Lampe de sol", "volume" => 0.25, "qte" => 0],
        ["id" => 81, "nom" => "Lampe de table", "volume" => 0.25, "qte" => 0],
        ["id" => 82, "nom" => "living grand", "volume" => 3.00, "qte" => 0],
        ["id" => 83, "nom" => "living petit", "volume" => 1.50, "qte" => 0],
        ["id" => 84, "nom" => "Meuble TV (moyen)", "volume" => 0.25, "qte" => 0],
        ["id" => 85, "nom" => "Meuble TV (complet / grand)", "volume" => 2.00, "qte" => 0],
        ["id" => 86, "nom" => "Miroir sur pied", "volume" => 0.25, "qte" => 0],
        ["id" => 87, "nom" => "Miroir grand", "volume" => 0.05, "qte" => 0],
        ["id" => 88, "nom" => "Miroir petit", "volume" => 0.01, "qte" => 0],
        ["id" => 89, "nom" => "Table basse (petite)", "volume" => 0.25, "qte" => 0],
        ["id" => 90, "nom" => "Table basse (moyenne)", "volume" => 0.50, "qte" => 0],
        ["id" => 91, "nom" => "Table basse (grande)", "volume" => 0.90, "qte" => 0],
        ["id" => 92, "nom" => "Tableau (grand)", "volume" => 0.04, "qte" => 0],
        ["id" => 93, "nom" => "Tableau (moyen)", "volume" => 0.02, "qte" => 0],
        ["id" => 94, "nom" => "Tableau (petit)", "volume" => 0.10, "qte" => 0],
        ["id" => 95, "nom" => "Table à manger (grande)", "volume" => 1.70, "qte" => 0],
        ["id" => 96, "nom" => "Table à manger (moyenne)", "volume" => 1.50, "qte" => 0],
        ["id" => 97, "nom" => "Table à manger (petite)", "volume" => 1.20, "qte" => 0],
        ["id" => 98, "nom" => "Tapis (grand)", "volume" => 0.50, "qte" => 0],
        ["id" => 99, "nom" => "Tapis (standard)", "volume" => 0.10, "qte" => 0],
        ["id" => 100, "nom" => "Tapis (petit)", "volume" => 0.03, "qte" => 0],
        ["id" => 101, "nom" => "TV grand écran", "volume" => 0.25, "qte" => 0],
        ["id" => 102, "nom" => "TV écran moyen", "volume" => 0.20, "qte" => 0],
        ["id" => 103, "nom" => "TV écran petit", "volume" => 0.15, "qte" => 0],
        ["id" => 104, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 105, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 106, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0],
        ["id" => 107, "nom" => "Cartons penderies", "volume" => 0.50, "qte" => 0]
    ],
    "divers" => [
        ["id" => 108, "nom" => "Aquarium (vide) 200l", "volume" => 0.50, "qte" => 0, "categorie" => "Divers"],
        ["id" => 109, "nom" => "Aquarium 75 l", "volume" => 0.30, "qte" => 0],
        ["id" => 110, "nom" => "Aquarium 30 l", "volume" => 0.30, "qte" => 0],
        ["id" => 111, "nom" => "Valise grande", "volume" => 0.16, "qte" => 0],
        ["id" => 112, "nom" => "Valise moyenne", "volume" => 0.13, "qte" => 0],
        ["id" => 113, "nom" => "Valise petite", "volume" => 0.06, "qte" => 0],
        ["id" => 114, "nom" => "Baby foot", "volume" => 2.00, "qte" => 0],
        ["id" => 115, "nom" => "Panier pour chien", "volume" => 0.08, "qte" => 0],
        ["id" => 116, "nom" => "Plante / arbuste (H > 2m)", "volume" => 1.00, "qte" => 0],
        ["id" => 117, "nom" => "Plante grande taille (H < 2m)", "volume" => 0.83, "qte" => 0],
        ["id" => 118, "nom" => "Plante moyenne taille (H < 1m)", "volume" => 0.17, "qte" => 0],
        ["id" => 119, "nom" => "Plante petite taille (H < 50cm)", "volume" => 0.02, "qte" => 0],
        ["id" => 120, "nom" => "Jardinière vide", "volume" => 0.10, "qte" => 0]
    ],
    "materiel" => [
        ["id" => 121, "nom" => "Aspirateur", "volume" => 0.10, "qte" => 0, "categorie" => "Materiel"],
        ["id" => 122, "nom" => "Climatiseur/ventilateur", "volume" => 0.50, "qte" => 0],
        ["id" => 123, "nom" => "mini chaine hifi", "volume" => 0.05, "qte" => 0],
        ["id" => 124, "nom" => "stéréo", "volume" => 0.15, "qte" => 0],
        ["id" => 125, "nom" => "Guitare", "volume" => 0.15, "qte" => 0],
        ["id" => 126, "nom" => "Imprimante", "volume" => 0.25, "qte" => 0],
        ["id" => 127, "nom" => "Machine à coudre +console", "volume" => 0.50, "qte" => 0],
        ["id" => 128, "nom" => "Machine à coudre portable", "volume" => 0.10, "qte" => 0],
        ["id" => 129, "nom" => "Matériel de sport", "volume" => 0.25, "qte" => 0],
        ["id" => 130, "nom" => "ecran ordinateur", "volume" => 0.25, "qte" => 0],
        ["id" => 131, "nom" => "Ordinateur (écran + uc + clavier)", "volume" => 0.25, "qte" => 0],
        ["id" => 132, "nom" => "Poussette / Siège auto", "volume" => 0.95, "qte" => 0],
        ["id" => 133, "nom" => "piano numerique", "volume" => 0.50, "qte" => 0],
        ["id" => 134, "nom" => "Synthétiseur", "volume" => 0.50, "qte" => 0],
        ["id" => 135, "nom" => "Table à langer", "volume" => 0.70, "qte" => 0],
        ["id" => 136, "nom" => "Table à repasser (+ fer)", "volume" => 0.10, "qte" => 0],
        ["id" => 137, "nom" => "Tour CD (grand modèle)", "volume" => 0.10, "qte" => 0],
        ["id" => 138, "nom" => "Tour CD (modèle bas)", "volume" => 0.04, "qte" => 0],
        ["id" => 139, "nom" => "Vélo d'appartement", "volume" => 1.50, "qte" => 0]
    ],
    "poidsLourds" => [
        ["id" => 140, "nom" => "Billard", "volume" => 3.00, "qte" => 0, "categorie" => "poids Lourds"],
        ["id" => 141, "nom" => "Coffre fort grand", "volume" => 0.50, "qte" => 0],
        ["id" => 142, "nom" => "Coffre fort petit", "volume" => 0.20, "qte" => 0],
        ["id" => 143, "nom" => "Piano droit", "volume" => 1.55, "qte" => 0],
        ["id" => 144, "nom" => "Piano à queue", "volume" => 3.70, "qte" => 0]
    ],
    "caveGrenier" => [
        ["id" => 145, "nom" => "Caddie de golf", "volume" => 0.25, "qte" => 0, "categorie" => "Cave/Grenier"],
        ["id" => 146, "nom" => "Cave à vin", "volume" => 1.00, "qte" => 0],
        ["id" => 147, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 148, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 149, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0]
    ],
    "chambre" => [
        ["id" => 150, "nom" => "Armoire 2 portes", "volume" => 2.00, "qte" => 0, "categorie" => "Chambre"],
        ["id" => 151, "nom" => "Armoire 2 portes coulissantes", "volume" => 2.50, "qte" => 0],
        ["id" => 152, "nom" => "Armoire 3 portes", "volume" => 2.50, "qte" => 0],
        ["id" => 153, "nom" => "Armoire 3 portes coulissantes", "volume" => 2.50, "qte" => 0],
        ["id" => 154, "nom" => "Armoire 4 portes", "volume" => 3.20, "qte" => 0],
        ["id" => 155, "nom" => "Armoire 5 portes", "volume" => 5.00, "qte" => 0],
        ["id" => 156, "nom" => "Armoire 6 portes", "volume" => 6.00, "qte" => 0],
        ["id" => 157, "nom" => "Armoire ancienne chevillée", "volume" => 2.00, "qte" => 0],
        ["id" => 158, "nom" => "Armoire penderie 1 porte", "volume" => 0.70, "qte" => 0],
        ["id" => 159, "nom" => "Armoire penderie 2 porte", "volume" => 1.25, "qte" => 0],
        ["id" => 160, "nom" => "Bureau double", "volume" => 1.50, "qte" => 0],
        ["id" => 161, "nom" => "Bureau Grand", "volume" => 1.50, "qte" => 0],
        ["id" => 162, "nom" => "Bureau Moyen", "volume" => 1.00, "qte" => 0],
        ["id" => 163, "nom" => "Bureau  Petit", "volume" => 0.75, "qte" => 0],
        ["id" => 164, "nom" => "Bureau d'Angle", "volume" => 2.00, "qte" => 0],
        ["id" => 165, "nom" => "Bureau ordinateur", "volume" => 1.00, "qte" => 0],
        ["id" => 166, "nom" => "Bureau avc partie supérieure", "volume" => 1.50, "qte" => 0],
        ["id" => 167, "nom" => "Fauteuil de bureau", "volume" => 0.30, "qte" => 0],
        ["id" => 168, "nom" => "Chaise", "volume" => 0.25, "qte" => 0],
        ["id" => 169, "nom" => "Clic clac", "volume" => 1.50, "qte" => 0],
        ["id" => 170, "nom" => "Coffre à jouets", "volume" => 0.25, "qte" => 0],
        ["id" => 171, "nom" => "Coffre /malle", "volume" => 0.50, "qte" => 0],
        ["id" => 172, "nom" => "Coffre petit", "volume" => 0.30, "qte" => 0],
        ["id" => 173, "nom" => "Commode (grande)", "volume" => 1.00, "qte" => 0],
        ["id" => 174, "nom" => "Commode (moyenne)", "volume" => 0.75, "qte" => 0],
        ["id" => 175, "nom" => "Commode (petite)", "volume" => 0.50, "qte" => 0],
        ["id" => 176, "nom" => "Commode (haute)", "volume" => 1.00, "qte" => 0],
        ["id" => 177, "nom" => "Commode fichier (2 tiroirs)", "volume" => 0.20, "qte" => 0],
        ["id" => 178, "nom" => "Commode fichier (3 tiroirs)", "volume" => 0.30, "qte" => 0],
        ["id" => 179, "nom" => "Commode fichier (4 tiroirs)", "volume" => 0.40, "qte" => 0],
        ["id" => 180, "nom" => "Commode fichier (5 tiroirs)", "volume" => 0.50, "qte" => 0],
        ["id" => 181, "nom" => "Fauteuil", "volume" => 1.00, "qte" => 0],
        ["id" => 182, "nom" => "Lampadaire", "volume" => 0.25, "qte" => 0],
        ["id" => 183, "nom" => "Lampe de sol", "volume" => 0.25, "qte" => 0],
        ["id" => 184, "nom" => "Lampe de table", "volume" => 0.25, "qte" => 0],
        ["id" => 185, "nom" => "Lampe de chevet", "volume" => 0.15, "qte" => 0],
        ["id" => 186, "nom" => "Lits superposés", "volume" => 2.00, "qte" => 0],
        ["id" => 187, "nom" => "Lit bébé", "volume" => 0.50, "qte" => 0],
        ["id" => 188, "nom" => "lit 160 (matelas+sommier)", "volume" => 2.00, "qte" => 0],
        ["id" => 189, "nom" => "lit 180 (matelas+sommier)", "volume" => 2.30, "qte" => 0],
        ["id" => 190, "nom" => "lit 140 (matelas+sommier)", "volume" => 1.60, "qte" => 0],
        ["id" => 191, "nom" => "lit king size (matelas+sommier)", "volume" => 3.00, "qte" => 0],
        ["id" => 192, "nom" => "lit Baldaquin démonté", "volume" => 2.00, "qte" => 0],
        ["id" => 193, "nom" => "Lit double (sommier + matelas)", "volume" => 1.50, "qte" => 0],
        ["id" => 194, "nom" => "Lit pont", "volume" => 5.30, "qte" => 0],
        ["id" => 195, "nom" => "Lit parapluie (pliable)", "volume" => 0.50, "qte" => 0],
        ["id" => 196, "nom" => "Lit simple (sommier + matelas)", "volume" => 1.00, "qte" => 0],
        ["id" => 197, "nom" => "Matelas 140*200", "volume" => 0.60, "qte" => 0],
        ["id" => 198, "nom" => "Matelas 160*200", "volume" => 1.10, "qte" => 0],
        ["id" => 199, "nom" => "Matelas 200*200", "volume" => 1.30, "qte" => 0],
        ["id" => 200, "nom" => "Matelas king size", "volume" => 1.30, "qte" => 0],
        ["id" => 201, "nom" => "Sommier 140*200", "volume" => 0.90, "qte" => 0],
        ["id" => 202, "nom" => "Sommier 160*200", "volume" => 1.00, "qte" => 0],
        ["id" => 203, "nom" => "Sommier 200*200", "volume" => 1.20, "qte" => 0],
        ["id" => 204, "nom" => "Sommier king size", "volume" => 1.30, "qte" => 0],
        ["id" => 205, "nom" => "Meuble étagère (petit)", "volume" => 0.50, "qte" => 0],
        ["id" => 206, "nom" => "Meuble étagère (moyenne)", "volume" => 0.75, "qte" => 0],
        ["id" => 207, "nom" => "Meuble étagère (grand)", "volume" => 1.00, "qte" => 0],
        ["id" => 208, "nom" => "Etagère Kallax 16 casiers", "volume" => 0.85, "qte" => 0],
        ["id" => 209, "nom" => "Etagère Kallax 8 casiers", "volume" => 0.45, "qte" => 0],
        ["id" => 210, "nom" => "Etagère Kallax 4 casiers", "volume" => 0.25, "qte" => 0],
        ["id" => 211, "nom" => "Meuble TV petit", "volume" => 0.25, "qte" => 0],
        ["id" => 212, "nom" => "Meuble TV (petit / bas)", "volume" => 0.50, "qte" => 0],
        ["id" => 213, "nom" => "Meuble TV (complet / grand)", "volume" => 2.00, "qte" => 0],
        ["id" => 214, "nom" => "Miroir sur pied", "volume" => 0.25, "qte" => 0],
        ["id" => 215, "nom" => "Miroir grand", "volume" => 0.05, "qte" => 0],
        ["id" => 216, "nom" => "Secrétaire", "volume" => 0.90, "qte" => 0],
        ["id" => 217, "nom" => "Miroir petit", "volume" => 0.01, "qte" => 0],
        ["id" => 218, "nom" => "Table de chevet", "volume" => 0.20, "qte" => 0],
        ["id" => 219, "nom" => "Tableau (grand)", "volume" => 0.04, "qte" => 0],
        ["id" => 220, "nom" => "Tableau (moyen)", "volume" => 0.02, "qte" => 0],
        ["id" => 221, "nom" => "Tableau (petit)", "volume" => 0.10, "qte" => 0],
        ["id" => 222, "nom" => "TV grand écran", "volume" => 0.25, "qte" => 0],
        ["id" => 223, "nom" => "TV écran moyen", "volume" => 0.20, "qte" => 0],
        ["id" => 224, "nom" => "TV écran petit", "volume" => 0.15, "qte" => 0],
        ["id" => 225, "nom" => "Meuble TV (moyen)", "volume" => 0.25, "qte" => 0],
        ["id" => 226, "nom" => "Meuble TV (complet / grand)", "volume" => 2.00, "qte" => 0],
        ["id" => 227, "nom" => "Ventilateur", "volume" => 0.20, "qte" => 0],
        ["id" => 228, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 229, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 230, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0],
        ["id" => 231, "nom" => "Cartons penderies", "volume" => 0.50, "qte" => 0]
    ],
    "garage" => [
        ["id" => 232, "nom" => "Banc de musculation grd", "volume" => 2.50, "qte" => 0, "categorie" => "Garage"],
        ["id" => 233, "nom" => "Banc de musculation petit", "volume" => 0.50, "qte" => 0],
        ["id" => 234, "nom" => "Banc de musculation moyen", "volume" => 1.75, "qte" => 0],
        ["id" => 235, "nom" => "Brouette", "volume" => 0.50, "qte" => 0],
        ["id" => 236, "nom" => "Cage/volière", "volume" => 0.50, "qte" => 0],
        ["id" => 237, "nom" => "Coffre de toit Grand", "volume" => 1.00, "qte" => 0],
        ["id" => 238, "nom" => "Coffre de toit Petit", "volume" => 0.30, "qte" => 0],
        ["id" => 239, "nom" => "Coffre à outils Grand", "volume" => 0.50, "qte" => 0],
        ["id" => 240, "nom" => "Coffre à outils Petit", "volume" => 0.25, "qte" => 0],
        ["id" => 241, "nom" => "Compresseur 100 l", "volume" => 1.40, "qte" => 0],
        ["id" => 242, "nom" => "Compresseur 50 l", "volume" => 0.40, "qte" => 0],
        ["id" => 243, "nom" => "Compresseur petit", "volume" => 0.60, "qte" => 0],
        ["id" => 244, "nom" => "Echelle, escabo", "volume" => 0.50, "qte" => 0],
        ["id" => 245, "nom" => "Etablis", "volume" => 1.00, "qte" => 0],
        ["id" => 246, "nom" => "Lot outils de jardin / ratelier", "volume" => 0.30, "qte" => 0],
        ["id" => 247, "nom" => "Moto", "volume" => 4.00, "qte" => 0],
        ["id" => 248, "nom" => "Outils de jardin", "volume" => 0.05, "qte" => 0],
        ["id" => 249, "nom" => "Parasol (avec pied)", "volume" => 0.20, "qte" => 0],
        ["id" => 250, "nom" => "Planche à voile", "volume" => 0.50, "qte" => 0],
        ["id" => 251, "nom" => "Pneu", "volume" => 0.25, "qte" => 0],
        ["id" => 252, "nom" => "Sac de golf", "volume" => 0.15, "qte" => 0],
        ["id" => 253, "nom" => "Skis (nombre de paires)", "volume" => 0.04, "qte" => 0],
        ["id" => 254, "nom" => "Tondeuse", "volume" => 1.00, "qte" => 0],
        ["id" => 255, "nom" => "Tondeuse autoportée / Tracteur", "volume" => 2.00, "qte" => 0],
        ["id" => 256, "nom" => "Trotinette / Skate board", "volume" => 0.10, "qte" => 0],
        ["id" => 257, "nom" => "Vélo", "volume" => 0.75, "qte" => 0],
        ["id" => 258, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 259, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 260, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0]
    ],
    "exterieur" => [
        ["id" => 261, "nom" => "Balancelle 3 places démontée", "volume" => 0.25, "qte" => 0, "categorie" => "Extérieur"],
        ["id" => 262, "nom" => "Balancelle pour bébé", "volume" => 0.50, "qte" => 0],
        ["id" => 263, "nom" => "Balançoire / démontée", "volume" => 1.00, "qte" => 0],
        ["id" => 264, "nom" => "Banc Grand", "volume" => 1.00, "qte" => 0],
        ["id" => 265, "nom" => "Banc petit", "volume" => 0.50, "qte" => 0],
        ["id" => 266, "nom" => "Banc de jardin", "volume" => 0.50, "qte" => 0],
        ["id" => 267, "nom" => "Barbecue Grand", "volume" => 1.00, "qte" => 0],
        ["id" => 268, "nom" => "Barbecue Petit", "volume" => 0.50, "qte" => 0],
        ["id" => 269, "nom" => "Chaise longue", "volume" => 0.50, "qte" => 0],
        ["id" => 270, "nom" => "Coffre  Extérieur grand", "volume" => 0.50, "qte" => 0],
        ["id" => 271, "nom" => "Coffre Etérieur  Petit", "volume" => 0.25, "qte" => 0],
        ["id" => 272, "nom" => "Poubelle de jardin", "volume" => 0.35, "qte" => 0],
        ["id" => 273, "nom" => "Poubelle Grande", "volume" => 0.55, "qte" => 0],
        ["id" => 274, "nom" => "Poubelle ¨Petite", "volume" => 0.15, "qte" => 0],
        ["id" => 275, "nom" => "Panier de basket (démonté)", "volume" => 0.25, "qte" => 0],
        ["id" => 276, "nom" => "Parabole (décrochée du toit)", "volume" => 0.10, "qte" => 0],
        ["id" => 277, "nom" => "Pot de fleurs vide Grand", "volume" => 1.40, "qte" => 0],
        ["id" => 278, "nom" => "Pot de fleurs vide Moyen", "volume" => 0.40, "qte" => 0],
        ["id" => 279, "nom" => "Pot de fleurs vide petit", "volume" => 0.10, "qte" => 0],
        ["id" => 280, "nom" => "Table de jardin", "volume" => 0.75, "qte" => 0],
        ["id" => 281, "nom" => "Chaise/fauteuil de jardin", "volume" => 0.25, "qte" => 0],
        ["id" => 282, "nom" => "Table de Ping Pong", "volume" => 1.20, "qte" => 0],
        ["id" => 283, "nom" => "Traiteaux", "volume" => 0.04, "qte" => 0],
        ["id" => 284, "nom" => "Planche 1 m", "volume" => 0.03, "qte" => 0],
        ["id" => 285, "nom" => "Planche 2 m", "volume" => 0.06, "qte" => 0],
        ["id" => 286, "nom" => "Planche 50 cm", "volume" => 0.01, "qte" => 0],
        ["id" => 287, "nom" => "Tuyau d'arrosage + enrouleur", "volume" => 0.10, "qte" => 0],
        ["id" => 288, "nom" => "Carton grand", "volume" => 0.10, "qte" => 0],
        ["id" => 289, "nom" => "Carton moyen", "volume" => 0.07, "qte" => 0],
        ["id" => 290, "nom" => "Carton petit", "volume" => 0.05, "qte" => 0]
    ]
];